name: publish

on: [push]

jobs:
  publish-predict-score-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the predict-score Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/tezpadhye/predict-score:latest
        docker run ghcr.io/tezpadhye/predict-score:latest
        docker push ghcr.io/tezpadhye/predict-score:latest
